#!/bin/bash

# Install Node.js
yes | sudo apt-get install python-software-properties
yes | sudo add-apt-repository ppa:chris-lea/node.js
yes | sudo apt-get update
yes | sudo apt-get install nodejs npm

# Install Dependencies
npm install -d

#create the backbone folders
mkdir assets/js/models
mkdir assets/js/collections
mkdir assets/js/views
mkdir assets/js/routers
